# Generated by Django 5.0 on 2023-12-15 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Company",
        ),
    ]
