# Generated by Django 5.0 on 2023-12-15 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company_app", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Licsense",
        ),
    ]
