# Generated by Django 5.0 on 2023-12-15 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_app", "0005_rename_erp_user_company_user"),
        ("main_app", "0006_remove_erp_plan_price_erp_plan_monthly_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company_Purchase_Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company_app.company",
                    ),
                ),
                (
                    "erp_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.erp_plan",
                    ),
                ),
            ],
        ),
    ]
