# Generated by Django 5.0 on 2023-12-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_app", "0006_company_purchase_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="company_purchase_plan",
            name="purchase_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
