# Generated by Django 5.0 on 2023-12-12 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="BusinessSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.businesscategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_code_image",
                    models.ImageField(blank=True, null=True, upload_to="qr_code"),
                ),
                (
                    "qr_code_unique_no",
                    models.CharField(
                        blank=True, max_length=250, null=True, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logo")),
                ("ifse", models.CharField(blank=True, max_length=40, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=40, null=True)),
                ("account_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("pincode", models.CharField(blank=True, max_length=6, null=True)),
                ("gst_number", models.CharField(blank=True, max_length=40, null=True)),
                ("pan_number", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "business_legal_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "business_trade_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "gst_registered_on",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("website", models.CharField(blank=True, max_length=100, null=True)),
                ("is_reseller", models.BooleanField(default=False)),
                (
                    "reseller_id",
                    models.CharField(blank=True, default=0, max_length=50, null=True),
                ),
                ("swift_code", models.CharField(blank=True, max_length=40, null=True)),
                ("upi_code", models.ImageField(blank=True, null=True, upload_to="upi")),
                (
                    "signature",
                    models.ImageField(blank=True, null=True, upload_to="signature"),
                ),
                ("status", models.IntegerField(blank=True, default=0, null=True)),
                ("active_status", models.IntegerField(default=0)),
                ("latitude", models.CharField(blank=True, max_length=250, null=True)),
                ("longitude", models.CharField(blank=True, max_length=250, null=True)),
                ("variant_status", models.BooleanField(default=True)),
                ("spec_status", models.BooleanField(default=True)),
                ("sync_status", models.BooleanField(default=True)),
                ("bulk_product_status", models.BooleanField(default=True)),
                ("customer_status", models.BooleanField(default=True)),
                ("purchase_order_mail_status", models.BooleanField(default=True)),
                ("vendor_mail_status", models.BooleanField(default=True)),
                ("hiring_status", models.BooleanField(default=True)),
                ("candidate_bulk_upload_status", models.BooleanField(default=True)),
                ("hiring_history_status", models.BooleanField(default=True)),
                ("attendance_status", models.BooleanField(default=True)),
                ("attendance_bulk_upload_status", models.BooleanField(default=True)),
                ("team_status", models.BooleanField(default=True)),
                ("leads_status", models.BooleanField(default=True)),
                ("sales_target_status", models.BooleanField(default=True)),
                ("customer_bulk_upload_status", models.BooleanField(default=True)),
                ("gst_filling_status", models.BooleanField(default=True)),
                ("email_calendar_invitaion", models.BooleanField(default=True)),
                (
                    "delivery_manages_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("manufacturing_status", models.BooleanField(default=False)),
                ("currency", models.CharField(blank=True, max_length=100, null=True)),
                ("flag", models.ImageField(blank=True, null=True, upload_to="flag")),
                ("is_real_time_sync", models.BooleanField(default=False)),
                ("is_active_status", models.BooleanField(default=True)),
                (
                    "business_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.businesssubcategory",
                    ),
                ),
                (
                    "erp_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
