# Generated by Django 5.0 on 2023-12-15 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_country_pincode_taxrate_state_city_taxtype_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Company",
        ),
    ]
