# Generated by Django 5.0 on 2023-12-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main_app", "0004_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Erp_Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=255, unique=True)),
                ("price", models.FloatField(max_length=255)),
                ("no_of_user", models.IntegerField()),
                ("module", models.ManyToManyField(blank=True, to="auth.group")),
            ],
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
